
services:
  redis:
    image: redis:7
    container_name: task_redis
    restart: unless-stopped

  auth_api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task_auth_api
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - backend/.env
    command: uvicorn auth_main:app --host 0.0.0.0 --port 8000
    ports:
      - "8001:8000"
    volumes:
      - ./backend/logs:/app/logs

  tasks_api_1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task_tasks_api_1
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - backend/.env
    command: uvicorn tasks_main:app --host 0.0.0.0 --port 8000
    ports:
      - "8002:8000"
    volumes:
      - ./backend/logs:/app/logs

  tasks_api_2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task_tasks_api_2
    restart: unless-stopped
    depends_on:
      - redis
    env_file:
      - backend/.env
    command: uvicorn tasks_main:app --host 0.0.0.0 --port 8000
    ports:
      - "8003:8000"
    volumes:
      - ./backend/logs:/app/logs

  nginx:
    image: nginx:1.27-alpine
    container_name: task_gateway
    restart: unless-stopped
    depends_on:
      - auth_api
      - tasks_api_1
      - tasks_api_2
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  frontend:
    image: node:20
    container_name: task_frontend
    working_dir: /app
    depends_on:
      - nginx
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"